### PR TITLE
update lottie dependencie to ^2.2.0

### PR DESCRIPTION
**Pull request by dagovalsusa**
I just updated the version of lottie library

### CODE REVIEW

**Comment by rakib205** [comment]
Lottie update is required. Can you please update your package?

**Comment by dagovalsusa** [comment]
@newtaDev is the repo still active?

**Comment by newtaDev** [comment]
@dagovalsusa  Thank you for the PR, really appreciate your effort will review and merge ASAP

> @newtaDev is the repo still active?

Yes

And I also have a plan to rebuild this project....  will try do it ASAP

**Comment by nicktt19** [comment]
I need that update Lottie dependence too, please help. Thank you.

**Comment by newtaDev** [comment]
We are no longer using `lottie`
Thank you

**Pull request closed without merging**
