### PR TITLE
Update package to support unlisted vimeo videos

### PR DESCRIPTION
**Pull request by rafaelmeteoro**
Add a param `hash` to support unlisted vimeo videos.

### CODE REVIEW

**Comment by newtaDev** [comment]
Thank you for the PR 🤗

**Review by newtaDev — COMMENTED** [review]
Thank you for the PR 🤗

**Comment by Joseph-Nathan** [comment]
is that in released now ?

**Comment by newtaDev** [comment]
> is that in released now ?

Not yet to `pub`
will deploy it today itself

**Pull request merged**
