### PR TITLE
Fixed Youtube videos not playing

### PR DESCRIPTION
**Pull request by GeorgeReda**

### CODE REVIEW

**Comment by AhsanFarooq0017** [comment]
I am facing the same issue can help me solve this error?

**Comment by TiluWeb** [comment]
@GeorgeReda Can you please merge it

**Comment by a-wallen** [comment]
I also need this @saitejavankayala

**Review by saitejavankayala — APPROVED** [review]

**Comment by TiluWeb** [comment]
@saitejavankayala Can you please resolve conflicts and merge it ?

**Pull request closed without merging**
