### PR TITLE
#66 support vimeo private video

### PR DESCRIPTION
**Pull request by dotkebi**
Hello.

I made it because I needed a vimeo private video function.

* example

```
   final Map<String, String> headers = <String, String>{};
      headers['Authorization'] = 'Bearer ${token}';

      _podPlayerController = PodPlayerController(
          playVideoFrom: PlayVideoFrom.vimeoPrivateVideos(
              '${vimeoVideoId}',
              httpHeaders: headers),
          podPlayerConfig: const PodPlayerConfig(
            videoQualityPriority: [1080, 720, 360],
            autoPlay: true,
            isLooping: true,
          ))
        ..initialise();
```

Thank you.

### CODE REVIEW

**Comment by newtaDev** [comment]
Hey @dotkebi , 
Thank you for your contribution 😍
Will verify and merge ASAP

**Comment by newtaDev** [comment]
@dotkebi 
Can you please add examples to `/examples`

**Comment by dotkebi** [comment]
@newtaDev 
I added an examples,
but it requires an access token of `vimeo` service, and private video id.

**Comment by newtaDev** [comment]
@dotkebi 
Please add a usage guide in Readme.md

**Comment by dotkebi** [comment]
@newtaDev 
update a usage guide in Readme.md

**Comment by newtaDev** [comment]
@dotkebi 
Thank you for PR, 
Really appreciate your effort 👏
Will merge 🤩

**Pull request merged**
