### PR TITLE
fix: Update http package

### PR DESCRIPTION
**Pull request by mbfakourii**
Update http package to ```http: ^1.0.0```

### CODE REVIEW

**Comment by newtaDev** [comment]
Thank you for the PR
But we cannot merge this PR now: 
 Because `youtube_explode_dart >=1.10.9` depends on
 `http ^0.13.4` and pod_player depends on `http ^1.1.0`

**Comment by JoshRice1** [comment]
Looks like youtube_explode_dart has been updated.  Any chance this PR can get merged now?

**Comment by mbenci** [comment]
The last version of youtube_explode_dart (2.0.1) depends on http ^1.0.0

**Comment by newtaDev** [comment]
Updated all dependencies

**Pull request closed without merging**
